[workspace]
authors = ["Anders Kaestner <anders.kaestner@psi.ch>"]
channels = ["astra-toolbox", "nvidia", "conda-forge"]
name = "scripts"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "*"
scipy = "*"
matplotlib = "*"
jupyter = "*"
notebook = "6.*"
pandas = "*"
scikit-learn = "*"
scikit-image = "*"
uncertainties = "*"
opencv = "*"
pandoc = "*"
jupyter-book = "*"
ipywidgets = "*"
ipyfilechooser = "*"
ipympl = "*"
astropy = "*"
dask = "*"
mysqlclient = "*"
seaborn = "*"
tifffile = "*"
tqdm = "*"
pytest = "*"
matplotlib-scalebar = "*"
ffmpeg = "*"
rise = "*"
jupyter_contrib_nbextensions = "*"
pyvista = "*"
trame = "*"
trame-vtk = "*"
trame-vuetify = "*"
plotly = "*"

[target.win-64.dependencies]
astra-toolbox = "*"